/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lasfiguras;

import javax.swing.JOptionPane;

/**
 *
 * @author stich
 */
public class cilindro extends javax.swing.JFrame {

    /**
     * Creates new form cilindro
     */
    public cilindro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 3), new java.awt.Dimension(0, 3), new java.awt.Dimension(32767, 3));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btncalcular = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtaltura = new javax.swing.JTextField();
        txtradio = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        txtvolumen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtperimetro = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtgeneratrizcono = new javax.swing.JTextField();
        txtradiocono = new javax.swing.JTextField();
        txtareacono = new javax.swing.JTextField();
        txtvolumencono = new javax.swing.JTextField();
        txtperimetrocono = new javax.swing.JTextField();
        btncalcularcono = new javax.swing.JButton();
        btnlimpiarcono = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtperimetrolateral = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtlongitudpa = new javax.swing.JTextField();
        txtanchopa = new javax.swing.JTextField();
        txtalturapa = new javax.swing.JTextField();
        txtareapa = new javax.swing.JTextField();
        txtvolumenpa = new javax.swing.JTextField();
        txtperimetropa = new javax.swing.JTextField();
        btncalcularpa = new javax.swing.JButton();
        btnlimpiarpa = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtradioes = new javax.swing.JTextField();
        txtradiocir = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtareaes = new javax.swing.JTextField();
        txtvolumenes = new javax.swing.JTextField();
        txtperimetroes = new javax.swing.JTextField();
        btncalculares = new javax.swing.JToggleButton();
        btnlimpiares = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cilindro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\stich\\Downloads\\R.jpg")); // NOI18N
        jLabel2.setText("Cilindro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 125, 165, -1));

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 189, 165, -1));

        jLabel3.setText("Altura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, 45, -1));

        jLabel4.setText("Radio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 159, 45, -1));

        jLabel5.setText("Area");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 188, 45, -1));

        jLabel6.setText("volumen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 217, 45, -1));

        txtaltura.setText("0");
        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 122, 103, -1));

        txtradio.setText("0");
        getContentPane().add(txtradio, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 159, 103, -1));
        getContentPane().add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 188, 103, -1));
        getContentPane().add(txtvolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 214, 103, -1));

        jLabel7.setText("Perimetro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, -1, -1));
        getContentPane().add(txtperimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 243, 103, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 371, 1007, 6));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cono");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 387, 44, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasfiguras/figuras-geométricas-86.gif"))); // NOI18N
        jLabel9.setText("Cono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 387, -1, 188));

        jLabel10.setText("Generatriz");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 584, 56, -1));

        jLabel11.setText("Radio");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 609, 36, -1));

        jLabel12.setText("Area");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 634, 36, -1));

        jLabel13.setText("Volumen");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 676, -1, -1));

        jLabel14.setText("Perimetro de la base");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 736, -1, -1));

        txtgeneratrizcono.setText("0");
        getContentPane().add(txtgeneratrizcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 581, 80, -1));

        txtradiocono.setText("0");
        getContentPane().add(txtradiocono, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 606, 80, -1));
        getContentPane().add(txtareacono, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 631, 80, -1));
        getContentPane().add(txtvolumencono, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 668, 80, -1));
        getContentPane().add(txtperimetrocono, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 733, 80, -1));

        btncalcularcono.setText("Calcular cono");
        btncalcularcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularconoActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 440, 131, -1));

        btnlimpiarcono.setText("Limpiar cono");
        btnlimpiarcono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarconoActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiarcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 484, 131, -1));

        jLabel15.setText("Perimetro lateral");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 699, 95, -1));

        txtperimetrolateral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperimetrolateralActionPerformed(evt);
            }
        });
        getContentPane().add(txtperimetrolateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 696, 80, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Paralelepipedo");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(873, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasfiguras/11.gif"))); // NOI18N
        jLabel17.setText("Paralelepipedo");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 10, -1, -1));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 188, 45, -1));

        jLabel24.setText("Longitud");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 203, -1, -1));

        jLabel25.setText("Ancho");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 230, 36, -1));

        jLabel26.setText("Altura");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 264, 36, -1));

        jLabel27.setText("Area");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 289, 36, -1));

        jLabel28.setText("Volumen");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 318, -1, -1));

        jLabel29.setText("Perimetro");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 344, -1, -1));

        txtlongitudpa.setText("0");
        getContentPane().add(txtlongitudpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 55, -1));

        txtanchopa.setText("0");
        getContentPane().add(txtanchopa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 225, 55, -1));

        txtalturapa.setText("0");
        getContentPane().add(txtalturapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 261, 55, -1));
        getContentPane().add(txtareapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 286, 55, -1));
        getContentPane().add(txtvolumenpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 315, 55, -1));
        getContentPane().add(txtperimetropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 344, 55, -1));

        btncalcularpa.setText("Calcular");
        btncalcularpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularpaActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 162, -1, -1));

        btnlimpiarpa.setText("limpiar");
        btnlimpiarpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarpaActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiarpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 189, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Esfera");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 387, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasfiguras/esfera.png"))); // NOI18N
        jLabel19.setText("Esfera");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 387, -1, 198));

        jLabel20.setText("Radio");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 606, 42, 19));

        jLabel22.setText("Radio del Circulo ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 635, -1, -1));

        txtradioes.setText("0");
        getContentPane().add(txtradioes, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 603, 55, -1));

        txtradiocir.setText("0");
        getContentPane().add(txtradiocir, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 632, 55, -1));

        jLabel23.setText("Area");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 661, 36, -1));

        jLabel30.setText("Volumen");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 690, -1, -1));

        jLabel31.setText("Perimetro");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 714, -1, -1));
        getContentPane().add(txtareaes, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 661, 55, -1));
        getContentPane().add(txtvolumenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 687, 55, -1));
        getContentPane().add(txtperimetroes, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 711, 55, -1));

        btncalculares.setText("Calcular");
        btncalculares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularesActionPerformed(evt);
            }
        });
        getContentPane().add(btncalculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 433, -1, -1));

        btnlimpiares.setText("Limpiar");
        btnlimpiares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiaresActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiares, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 476, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        double altura,area,radio,radio2,volumen,perimetro;
        if(txtaltura.getText().equals("")){
            JOptionPane.showConfirmDialog(null,"Ingrese altura");
            txtaltura.requestFocus();
        }else{
            if(txtradio.getText().equals("")){
                 JOptionPane.showConfirmDialog(null,"Ingrese radio");
             txtradio.requestFocus();
            }else{
               altura=Double.parseDouble(txtaltura.getText());
                radio=Double.parseDouble(txtradio.getText());
                
                area=(2*Math.PI*radio*(altura+radio));
                radio2=Math.pow(radio,2);
                
                volumen=(Math.PI*radio2*altura);
                perimetro=(2*Math.PI*radio+2*altura);
                txtarea.setText(area+"");
                txtvolumen.setText(volumen+"");
                txtperimetro.setText(perimetro+"");
            }
        }
    }//GEN-LAST:event_btncalcularActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        txtaltura.setText("");
        txtarea.setText("");
        txtradio.setText("");
        txtvolumen.setText("");
        txtperimetro.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btncalcularconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularconoActionPerformed
        // TODO add your handling code here:
        double generatrizcono,areacono,radiocono,radio2,volumencono,perimetrocono,perimetrolateral;
        if(txtgeneratrizcono.getText().equals("")){
            JOptionPane.showConfirmDialog(null,"Ingrese la generatriz");
            txtgeneratrizcono.requestFocus();
        }else{
            if(txtradiocono.getText().equals("")){
                 JOptionPane.showConfirmDialog(null,"Ingrese radio");
             txtradiocono.requestFocus();
            }else{
               generatrizcono=Double.parseDouble(txtgeneratrizcono.getText());
                radiocono=Double.parseDouble(txtradiocono.getText());
                
                areacono=(Math.PI * radiocono * (radiocono + generatrizcono));
                radio2=Math.pow(radiocono,2);
                perimetrolateral = Math.PI * radiocono * generatrizcono;
                volumencono=(Math.PI*radio2*generatrizcono);
                perimetrocono=Math.PI * Math.pow(radiocono, 2);
                txtareacono.setText(areacono+"");
                txtvolumencono.setText(volumencono+"");
                txtperimetrocono.setText(perimetrocono+"");
                txtperimetrolateral.setText(perimetrolateral+"");
            }
        }
    }//GEN-LAST:event_btncalcularconoActionPerformed

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    private void txtperimetrolateralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperimetrolateralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperimetrolateralActionPerformed

    private void btnlimpiarconoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarconoActionPerformed
        // TODO add your handling code here:
        txtgeneratrizcono.setText("");
        txtareacono.setText("");
        txtradiocono.setText("");
        txtvolumencono.setText("");
        txtperimetrocono.setText("");
        txtperimetrolateral.setText("");
    }//GEN-LAST:event_btnlimpiarconoActionPerformed

    private void btncalcularpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularpaActionPerformed
        // TODO add your handling code here:
        double alturapa,areapa,volumenpa,perimetropa,anchopa,longitudpa;
        if(txtaltura.getText().equals("")){
            JOptionPane.showConfirmDialog(null,"alturapa");
            txtalturapa.requestFocus();
        }else{
            if(txtlongitudpa.getText().equals("")){
                JOptionPane.showConfirmDialog(null,"longitudpa");
                txtlongitudpa.requestFocus();
            }else{
                if(txtanchopa.getText().equals("")){
                    JOptionPane.showConfirmDialog(null,"anchopa");
                    txtanchopa.requestFocus();
                }else{
                    alturapa=Double.parseDouble(txtalturapa.getText());
                    longitudpa=Double.parseDouble(txtlongitudpa.getText());
                    anchopa=Double.parseDouble(txtanchopa.getText());
                    
                    areapa= 2*(longitudpa*anchopa+longitudpa*alturapa+anchopa*alturapa);
                    volumenpa= longitudpa*anchopa*alturapa;
                    perimetropa=2*(longitudpa+anchopa);
                    txtareapa.setText(areapa+"");
                    txtvolumenpa.setText(volumenpa+"");
                    txtperimetropa.setText(perimetropa+"");
                    
                }
                
            }
        }
    }//GEN-LAST:event_btncalcularpaActionPerformed

    private void btnlimpiarpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarpaActionPerformed
        // TODO add your handling code here:
        txtalturapa.setText("");
        txtareapa.setText("");
        txtanchopa.setText("");
        txtvolumenpa.setText("");
        txtperimetropa.setText("");
        txtlongitudpa.setText("");
        
    }//GEN-LAST:event_btnlimpiarpaActionPerformed

    private void btncalcularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularesActionPerformed
        // TODO add your handling code here:
        double radioes,radiocir,perimetroes,areaes,volumenes;
        if(txtradioes.getText().equals("")){
            JOptionPane.showConfirmDialog(null, "ingrese el radioes");
           txtradioes.requestFocus();
        }else{
            if(txtradiocir.getText().equals("")){
            JOptionPane.showConfirmDialog(null,"ingrese el radiocir");
            txtradiocir.requestFocus();
            }else{
              radioes=Double.parseDouble(txtradioes.getText());
              radiocir=Double.parseDouble(txtradiocir.getText());
              
              areaes=4 * Math.PI *Math.pow(radioes, 2);
              volumenes=(4.0/3.0)* Math.PI * Math.pow(radioes,3);
              perimetroes=2 * Math.PI*radiocir;
              txtareaes.setText(areaes+"");
              txtvolumenes.setText(volumenes+"");
              txtperimetroes.setText(perimetroes+"");                     
        }
        }
    }//GEN-LAST:event_btncalcularesActionPerformed

    private void btnlimpiaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiaresActionPerformed
        // TODO add your handling code here:
        txtradioes.setText("");
        txtradiocir.setText("");
        txtareaes.setText("");
        txtvolumenes.setText("");
        txtperimetroes.setText("");
        
    }//GEN-LAST:event_btnlimpiaresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cilindro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cilindro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncalcularcono;
    private javax.swing.JToggleButton btncalculares;
    private javax.swing.JButton btncalcularpa;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnlimpiarcono;
    private javax.swing.JToggleButton btnlimpiares;
    private javax.swing.JButton btnlimpiarpa;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtalturapa;
    private javax.swing.JTextField txtanchopa;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtareacono;
    private javax.swing.JTextField txtareaes;
    private javax.swing.JTextField txtareapa;
    private javax.swing.JTextField txtgeneratrizcono;
    private javax.swing.JTextField txtlongitudpa;
    private javax.swing.JTextField txtperimetro;
    private javax.swing.JTextField txtperimetrocono;
    private javax.swing.JTextField txtperimetroes;
    private javax.swing.JTextField txtperimetrolateral;
    private javax.swing.JTextField txtperimetropa;
    private javax.swing.JTextField txtradio;
    private javax.swing.JTextField txtradiocir;
    private javax.swing.JTextField txtradiocono;
    private javax.swing.JTextField txtradioes;
    private javax.swing.JTextField txtvolumen;
    private javax.swing.JTextField txtvolumencono;
    private javax.swing.JTextField txtvolumenes;
    private javax.swing.JTextField txtvolumenpa;
    // End of variables declaration//GEN-END:variables
}
